# helm-charts/petclinic-umbrella/Chart.yaml
apiVersion: v2
name: petclinic-umbrella
description: Umbrella chart for Spring PetClinic Microservices
type: application
version: 0.1.0
appVersion: "3.4.1" # Example

dependencies:
  - name: config-server
    version: "0.1.0"
    repository: "file://./charts/config-server"
  - name: discovery-server
    version: "0.1.0"
    repository: "file://./charts/discovery-server"
  - name: customers-service
    version: "0.1.0"
    repository: "file://./charts/customers-service"
  - name: api-gateway
    version: "0.1.0"
    repository: "file://./charts/api-gateway"
  - name: vets-service
    version: "0.1.0"
    repository: "file://./charts/vets-service"
  - name: visits-service
    version: "0.1.0"
    repository: "file://./charts/visits-service"