# helm-charts/petclinic-umbrella/Chart.yaml
apiVersion: v2
name: petclinic-umbrella
description: Umbrella chart for Spring PetClinic Microservices
type: application
version: 0.1.0
appVersion: "3.4.1"

dependencies:
  - name: config-server
    version: "0.1.0"
    repository: "file://./charts/config-server"
  - name: discovery-server
    version: "0.1.0"
    repository: "file://./charts/discovery-server"
  - name: customers-service
    version: "0.1.0"
    repository: "file://./charts/customers-service"
    condition: customersService.enabled # <-- Add condition
  - name: api-gateway
    version: "0.1.0"
    repository: "file://./charts/api-gateway"
    condition: apiGateway.enabled # <-- Add condition
  - name: vets-service
    version: "0.1.0"
    repository: "file://./charts/vets-service"
    condition: vetsService.enabled # <-- Add condition
  - name: visits-service
    version: "0.1.0"
    repository: "file://./charts/visits-service"
    condition: visitsService.enabled # <-- Add condition
  - name: admin-server
    version: "0.1.0"
    repository: "file://./charts/admin-server"
    condition: adminServer.enabled # <-- Add condition
  - name: genai-service
    version: "0.1.0"
    repository: "file://./charts/genai-service"
    condition: genaiService.enabled # <-- Add condition