# helm-charts/petclinic-umbrella/values.yaml

configServer:
  image:
    tag: latest

discoveryServer:
  image:
    tag: latest

customersService:
  enabled: true # <-- Add flag
  image:
    tag: latest

apiGateway:
  enabled: true # <-- Add flag
  image:
    tag: latest
  service:
    nodePort: 30080 # Keep this uncommented if you want the static port

vetsService:
  enabled: true # <-- Add flag
  image:
    tag: latest

visitsService:
  enabled: true # <-- Add flag
  image:
    tag: latest

adminServer:
  enabled: false # <-- Add flag
  image:
    tag: latest

genaiService:
  enabled: false # <-- Add flag
  image:
    tag: latest