# This Service acts as an alias for applications hardcoded to use 'config-server' hostname
apiVersion: v1
kind: Service
metadata:
  # NOTE: Use the short name the application is looking for
  name: config-server
  # Add labels for consistency, using the main chart's helpers
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP # Matches the type of the main service
  ports:
    - port: {{ .Values.service.port }} # Use the same port as the main service (8888)
      targetPort: http # Target the same container port name
      protocol: TCP
      name: http
  # --- IMPORTANT: Use the SAME selector as the main service ---
  # This ensures this alias service targets the actual config-server pods
  selector:
    {{- include "config-server.selectorLabels" . | nindent 4 }}