# helm-charts/petclinic-umbrella/charts/config-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} # Target port should match container port
      protocol: TCP
      name: http
  selector:
    {{- include "config-server.selectorLabels" . | nindent 4 }}