# Default values for discovery-server.
# Overridden by the parent chart (petclinic-umbrella) or --set flags.

replicaCount: 1

image:
  repository: "" # Template constructs this: <global.dockerHubUser>/spring-petclinic-discovery-server
  pullPolicy: IfNotPresent
  tag: "" # Default tag managed by the parent chart/deployment command

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  # --- Set correct default service type and port ---
  type: ClusterIP # Internal service
  port: 8761     # Default port for discovery-server (Eureka)

ingress:
  enabled: false

# Default resource requests and limits for this service.
# {} uses global values from umbrella chart by default.
resources: {}
  # limits:
  #   memory: 512Mi
  # requests:
  #   memory: 256Mi
  #   cpu: 100m

autoscaling:
  enabled: false

# Liveness and Readiness Probes using Spring Boot Actuator
# Eureka might take a bit longer to be ready.
probes:
  liveness:
    enabled: true
    path: "/actuator/health/liveness"
    initialDelaySeconds: 45 # Longer delay for discovery server?
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    enabled: true
    path: "/actuator/health/readiness"
    initialDelaySeconds: 25 # Longer delay for discovery server?
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# Environment variables specific to this service (if any)
env: []

nodeSelector: {}
tolerations: []
affinity: {}