# helm-charts/petclinic-umbrella/charts/discovery-server/values.yaml

replicaCount: 1

image:
  # Use your Docker Hub username and the correct image name prefix
  repository: 22127422/spring-petclinic-discovery-server
  pullPolicy: IfNotPresent
  # tag - Default tag, overridden by Jenkins during deployment.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP # Internal service only
  port: 8761     # Default Eureka port

# Specific configuration for the discovery server application
# Often configured via Spring Cloud Config, so fewer direct values needed here.

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 512Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}