# Default values for discovery-server.
# Overridden by the parent chart (petclinic-umbrella) or --set flags.

replicaCount: 1

image:
  repository: "" # Template constructs this: <global.dockerHubUser>/spring-petclinic-discovery-server
  pullPolicy: IfNotPresent
  tag: "" # Default tag managed by the parent chart/deployment command

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  # --- Set correct default service type and port ---
  type: ClusterIP # Internal service
  port: 8761     # Default port for discovery-server (Eureka)

ingress:
  enabled: false

# Default resource requests and limits for this service.
# {} uses global values from umbrella chart by default.
resources: {}
  # limits:
  #   memory: 512Mi
  # requests:
  #   memory: 256Mi
  #   cpu: 100m

autoscaling:
  enabled: false

# Liveness and Readiness Probes using Spring Boot Actuator
# Eureka might take a bit longer to be ready.
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false

# Environment variables specific to this service (if any)
env:
  # Attempt to disable the config client entirely during bootstrap
  - name: SPRING_CLOUD_CONFIG_ENABLED
    value: "false"

nodeSelector: {}
tolerations: []
affinity: {}