# helm-charts/petclinic-umbrella/charts/api-gateway/Chart.yaml
apiVersion: v2
name: api-gateway
description: Helm chart for Spring PetClinic API Gateway
type: application
version: 0.1.0
appVersion: "3.4.1" # Example, use appropriate app version