# helm-charts/petclinic-umbrella/charts/api-gateway/values.yaml

replicaCount: 1

image:
  # Use your Docker Hub username and the correct image name prefix
  repository: 22127422/spring-petclinic-api-gateway
  pullPolicy: IfNotPresent
  # tag - Default tag, overridden by Jenkins during deployment.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  # Set type to NodePort to expose the gateway externally as per project requirements
  type: NodePort
  port: 8080     # API Gateway port
  # nodePort: Optional - Specify a static NodePort (e.g., 30080) or leave empty for dynamic assignment.
  # We can define this globally in the umbrella chart later if needed.
  nodePort: ""

# API Gateway specific configuration - most routing comes from Config Server/Discovery

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 256Mi # Adjust as needed
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}