apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }} # Uses helper
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }} # Uses helper
spec:
  type: {{ .Values.service.type }} # Uses type from values (ClusterIP default, overridden by parent)
  ports:
    - port: {{ .Values.service.port }} # Uses port from values (8080)
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }} # Uses helper