apiVersion: v1
kind: Service
metadata:
  # Explicitly set the name for clarity, though not strictly required for internal DNS here
  name: api-gateway
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }} # Use labels helper
spec:
  type: {{ .Values.service.type }} # Should be NodePort
  ports:
    - port: {{ .Values.service.port }} # Should be 8080
      targetPort: http # Reference the named port 'http' from the deployment
      protocol: TCP
      name: http # Name the service port
      # Only include nodePort if a value is provided in values.yaml
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }} # Use selector labels helper