apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-server.fullname" . }} # Use fullname helper
  labels:
    {{- include "discovery-server.labels" . | nindent 4 }} # Use labels helper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "discovery-server.selectorLabels" . | nindent 6 }} # Use selector labels helper
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "discovery-server.selectorLabels" . | nindent 8 }} # Use selector labels helper
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "discovery-server.serviceAccountName" . }} # Use service account name helper
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }} # Use chart name for container name
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http # Define a name for the port
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
            # Add environment variables from values.yaml if any are defined
            {{- range $key, $value := .Values.deployment.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          # Liveness Probe Configuration
          {{- if .Values.deployment.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.liveness.path }}
              port: http # Reference the named port
            initialDelaySeconds: {{ .Values.deployment.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.deployment.probes.liveness.successThreshold }}
          {{- end }}
          # Readiness Probe Configuration
          {{- if .Values.deployment.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.readiness.path }}
              port: http # Reference the named port
            initialDelaySeconds: {{ .Values.deployment.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.deployment.probes.readiness.successThreshold }}
          {{- end }}
          resources:
             {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}