# helm-charts/petclinic-umbrella/charts/discovery-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-server.fullname" . }}
  labels:
    {{- include "discovery-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "discovery-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "discovery-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "discovery-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-config-server
          image: busybox:1.36
          # --- MODIFY THIS LINE ---
          command: ['sh', '-c', 'until nc -z -w 2 petclinic-dev-config-server 8888; do echo waiting for config-server; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONFIG_SERVER_URL
              value: "http://{{ .Release.Name }}-config-server:8888"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - name: http-eureka
              containerPort: {{ .Values.service.port }} # Use the service port value (8761)
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness # Assuming Spring Boot Actuator health check
              port: http-eureka
            initialDelaySeconds: 45 # Give more time for discovery server potentially
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness # Assuming Spring Boot Actuator health check
              port: http-eureka
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      