# helm-charts/petclinic-umbrella/charts/discovery-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-server.fullname" . }}
  labels:
    {{- include "discovery-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} # Target Eureka port
      protocol: TCP
      name: http-eureka
  selector:
    {{- include "discovery-server.selectorLabels" . | nindent 4 }}