# helm-charts/petclinic-umbrella/charts/genai-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-service.fullname" . }}
  labels:
    {{- include "genai-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} # Target genai-service port (8084)
      protocol: TCP
      name: http
  selector:
    {{- include "genai-service.selectorLabels" . | nindent 4 }}