# helm-charts/petclinic-umbrella/charts/customers-service/values.yaml

replicaCount: 1

image:
  # Use your Docker Hub username and the correct image name prefix
  repository: 22127422/spring-petclinic-customers-service
  pullPolicy: IfNotPresent
  # tag - Default tag, overridden by Jenkins during deployment.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP # Internal service only
  port: 8081     # Customers service port

# Specific configuration for the customers service application
# Often configured via Spring Cloud Config.

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 256Mi # Adjust as needed
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}